### ISSUE TITLE
Attached Placement Error

### ISSUE THREAD

**Issue by dham-eng** [DeepSOIC/Lattice2#48]
Hello,

When trying to use the Attached Placement function, this error happens, independently of what is selected, be it a vertex, a line, a surface or nothing:
![Lattice2 - Attached Placement Error](https://user-images.githubusercontent.com/16336129/83187198-c6c11700-a0fb-11ea-9d2f-1b6a02389829.png)
`Traceback (most recent call last):
  File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\lattice2\lattice2AttachablePlacement.py", line 207, in Activated
    CreateAttachablePlacement(name= "Placment")
  File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\lattice2\lattice2AttachablePlacement.py", line 173, in CreateAttachablePlacement
    FreeCADGui.doCommand("f = lattice2AttachablePlacement.makeAttachablePlacement(name='"+name+"')")
  File "<string>", line 1, in <module>
  File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\lattice2\lattice2AttachablePlacement.py", line 46, in makeAttachablePlacement
    obj = FreeCAD.ActiveDocument.addObject("Part::AttachableObjectPython",name)
Base.FreeCADError: No document object found of type 'Part::AttachableObjectPython'
`
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Portuguese/Brazil (pt_BR)

**Comment by DeepSOIC** [comment]
thanks for reporting. It is caused by odd versioning system of stable releases, they are not treated correctly by Lattice2. Will fix.
